# treba videti kako pokrenuti node aplikaciju preko package.json-a
---
- hosts: all
  become: true
  remote_user: vagrant
  vars:
    url: testing.dev
    document_root: /var/www
    nodejs_setup_version: setup_9.x
  tasks:
    - name: Update APT Cache
      apt: update_cache=yes

    - name: Install Essentials, Nginx, Curl, Git ...
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - nginx
        - curl
        - git
        - htop

    - name: Download and run NodeJs setup ...
      shell: curl -sL https://deb.nodesource.com/{{nodejs_setup_version}} | sudo -E bash -
      register: result

    - debug:
        var: result

    - name: Install NodeJs ...
      apt: name=nodejs state=present

    - name: Install global NPM packages ...
      npm: name={{item}} global=yes
      with_items:
        - pm2

    - name: Copy accross virtual hosts ...
      template:
        src=templates/nginx.template.j2
        dest=/etc/nginx/sites-available/{{url}}

    - name: Enable site ...
      file:
        src=/etc/nginx/sites-available/{{url}}
        dest=/etc/nginx/sites-enabled/{{url}}
        state=link

    - name: Remove default config link ...
      file:
        path=/etc/nginx/sites-enabled/default
        state=absent

    - name: Kill all PM2 Apps ...
      command: pm2 kill
      args:
        chdir: "{{document_root}}"

    - name: Run app ...
      command: pm2 start server.js --name=FeApp
      args:
        chdir: "{{document_root}}"

    - name: Restart nginx
      service: name=nginx state=restarted
